<?php return array(
    'root' => array(
        'pretty_version' => '2.19.0',
        'version' => '2.19.0.0',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../../',
        'aliases' => array(),
        'reference' => NULL,
        'name' => 'anibalsanchez/xtplatform',
        'dev' => false,
    ),
    'versions' => array(
        'anibalsanchez/create-pattern' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../anibalsanchez/create-pattern',
            'aliases' => array(),
            'reference' => '4e739df39dacd28b414e4f040f790504e9f0e65c',
            'dev_requirement' => false,
        ),
        'anibalsanchez/extly-html-asset-tags-builder' => array(
            'pretty_version' => '1.8.0',
            'version' => '1.8.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../anibalsanchez/extly-html-asset-tags-builder',
            'aliases' => array(),
            'reference' => '7a1edb3d808ef35437091498ca5239a257e4c791',
            'dev_requirement' => false,
        ),
        'anibalsanchez/extly-infrastructure-cms-contract' => array(
            'pretty_version' => '1.10.1',
            'version' => '1.10.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../anibalsanchez/extly-infrastructure-cms-contract',
            'aliases' => array(),
            'reference' => '6ec0f38cec8aee3ca58f7ac78429297d0f1cccd2',
            'dev_requirement' => false,
        ),
        'anibalsanchez/extly-infrastructure-support' => array(
            'pretty_version' => '1.100.0',
            'version' => '1.100.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../anibalsanchez/extly-infrastructure-support',
            'aliases' => array(),
            'reference' => '153c9ef48276ddef4b7df61bbe59727ad362e071',
            'dev_requirement' => false,
        ),
        'anibalsanchez/xtplatform' => array(
            'pretty_version' => '2.19.0',
            'version' => '2.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../../',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
        'clue/stream-filter' => array(
            'pretty_version' => 'v1.5.0',
            'version' => '1.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../clue/stream-filter',
            'aliases' => array(),
            'reference' => 'aeb7d8ea49c7963d3b581378955dbf5bc49aa320',
            'dev_requirement' => false,
        ),
        'danielstjules/stringy' => array(
            'pretty_version' => '3.1.0',
            'version' => '3.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../danielstjules/stringy',
            'aliases' => array(),
            'reference' => 'df24ab62d2d8213bbbe88cc36fc35a4503b4bd7e',
            'dev_requirement' => false,
        ),
        'doctrine/inflector' => array(
            'pretty_version' => 'v1.1.0',
            'version' => '1.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/inflector',
            'aliases' => array(),
            'reference' => '90b2128806bfde671b6952ab8bea493942c1fdae',
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '1.8.3',
            'version' => '1.8.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'reference' => '1afdd860a2566ed3c2b0b4a3de6e23434a79ec85',
            'dev_requirement' => false,
        ),
        'illuminate/contracts' => array(
            'pretty_version' => 'v5.4.36',
            'version' => '5.4.36.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/contracts',
            'aliases' => array(),
            'reference' => '67f642e018f3e95fb0b2ebffc206c3200391b1ab',
            'dev_requirement' => false,
        ),
        'illuminate/support' => array(
            'pretty_version' => 'v5.4.36',
            'version' => '5.4.36.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/support',
            'aliases' => array(),
            'reference' => 'feab1d1495fd6d38970bd6c83586ba2ace8f299a',
            'dev_requirement' => false,
        ),
        'jeremykendall/php-domain-parser' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'kylekatarnls/update-helper' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'league/uri' => array(
            'pretty_version' => '4.2.3',
            'version' => '4.2.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/uri',
            'aliases' => array(),
            'reference' => 'e7a31846c3f00c190bd2817a36e943c22a1e2512',
            'dev_requirement' => false,
        ),
        'mtdowling/cron-expression' => array(
            'pretty_version' => 'v1.2.3',
            'version' => '1.2.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mtdowling/cron-expression',
            'aliases' => array(),
            'reference' => '9be552eebcc1ceec9776378f7dcc085246cacca6',
            'dev_requirement' => false,
        ),
        'myclabs/php-enum' => array(
            'pretty_version' => '1.6.6',
            'version' => '1.6.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/php-enum',
            'aliases' => array(),
            'reference' => '32c4202886c51fbe5cc3a7c34ec5c9a4a790345e',
            'dev_requirement' => false,
        ),
        'neitanod/forceutf8' => array(
            'pretty_version' => 'v2.0.4',
            'version' => '2.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neitanod/forceutf8',
            'aliases' => array(),
            'reference' => 'c1fbe70bfb5ad41b8ec5785056b0e308b40d4831',
            'dev_requirement' => false,
        ),
        'nesbot/carbon' => array(
            'pretty_version' => '1.39.1',
            'version' => '1.39.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nesbot/carbon',
            'aliases' => array(),
            'reference' => '4be0c005164249208ce1b5ca633cd57bdd42ff33',
            'dev_requirement' => false,
        ),
        'paragonie/random_compat' => array(
            'pretty_version' => 'v2.0.20',
            'version' => '2.0.20.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/random_compat',
            'aliases' => array(),
            'reference' => '0f1f60250fccffeaf5dda91eea1c018aed1adc2a',
            'dev_requirement' => false,
        ),
        'php-http/async-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'php-http/client-common' => array(
            'pretty_version' => '1.11.0',
            'version' => '1.11.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/client-common',
            'aliases' => array(),
            'reference' => '11d34cad40647848aa98536494f9da63571af9da',
            'dev_requirement' => false,
        ),
        'php-http/client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'php-http/curl-client' => array(
            'pretty_version' => 'v1.7.1',
            'version' => '1.7.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/curl-client',
            'aliases' => array(),
            'reference' => '6341a93d00e5d953fc868a3928b5167e6513f2b6',
            'dev_requirement' => false,
        ),
        'php-http/discovery' => array(
            'pretty_version' => '1.6.1',
            'version' => '1.6.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/discovery',
            'aliases' => array(),
            'reference' => '684855f2c2e9d0a61868b8f8d6bd0295c8a4b651',
            'dev_requirement' => false,
        ),
        'php-http/httplug' => array(
            'pretty_version' => 'v1.1.0',
            'version' => '1.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/httplug',
            'aliases' => array(),
            'reference' => '1c6381726c18579c4ca2ef1ec1498fdae8bdf018',
            'dev_requirement' => false,
        ),
        'php-http/message' => array(
            'pretty_version' => '1.7.2',
            'version' => '1.7.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/message',
            'aliases' => array(),
            'reference' => 'b159ffe570dffd335e22ef0b91a946eacb182fa1',
            'dev_requirement' => false,
        ),
        'php-http/message-factory' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/message-factory',
            'aliases' => array(),
            'reference' => 'a478cb11f66a6ac48d8954216cfed9aa06a501a1',
            'dev_requirement' => false,
        ),
        'php-http/message-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'php-http/promise' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/promise',
            'aliases' => array(),
            'reference' => 'dc494cdc9d7160b9a09bd5573272195242ce7980',
            'dev_requirement' => false,
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'reference' => 'f6561bf28d520154e4b0ec72be95418abe6d9363',
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'dev_requirement' => false,
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'dev_requirement' => false,
        ),
        'studiow/html' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../studiow/html',
            'aliases' => array(),
            'reference' => '860a6d4ff85bc25df5b9e0293d7ff916db8e01af',
            'dev_requirement' => false,
        ),
        'symfony/options-resolver' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/options-resolver',
            'aliases' => array(),
            'reference' => 'c7efc97a47b2ebaabc19d5b6c6b50f5c37c92744',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-iconv' => array(
            'pretty_version' => 'v1.19.0',
            'version' => '1.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-iconv',
            'aliases' => array(),
            'reference' => '085241787d52fa6f7a774fd034135fef0cfd5496',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'v1.19.0',
            'version' => '1.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(),
            'reference' => '4ad5115c0f5d5172a9fe8147675ec6de266d8826',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.19.0',
            'version' => '1.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'reference' => '8db0ae7936b42feb370840cf24de1a144fb0ef27',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.19.0',
            'version' => '1.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'reference' => 'b5f7b932ee6fa802fc792eabd77c4c88084517ce',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php70' => array(
            'pretty_version' => 'v1.19.0',
            'version' => '1.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php70',
            'aliases' => array(),
            'reference' => '3fe414077251a81a1b15b1c709faf5c2fbae3d4e',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php72' => array(
            'pretty_version' => 'v1.19.0',
            'version' => '1.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php72',
            'aliases' => array(),
            'reference' => 'beecef6b463b06954638f02378f52496cb84bacc',
            'dev_requirement' => false,
        ),
        'symfony/translation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'tightenco/collect' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.4.36',
            ),
        ),
    ),
);
