---
- hosts: all
  become: false
  vars:
    workspace: "{{ lookup('env','WORKSPACE') }}"
  vars_files: ["secrets/{{site_id}}","secrets/ssh_passwords"]
  tasks:
  - name: Create configuration.php
    template:
      src: "{{ config_src }}"
      dest: "{{ doc_root }}/configuration.php"
      owner: "{{ server_runs_as }}"
      group: "{{ server_runs_as_group }}"

  - name: Create .htversion file
    file:
      path: "{{ doc_root }}/.htversion"
      state: touch
      owner: "{{ server_runs_as }}"
      group: "{{ server_runs_as_group }}"

  - name: Write commit number .htversion to file
    shell: echo "{{ lookup('env','BUILD_NUMBER') }}" > {{ doc_root }}/.htversion

  - name: Take backup of db before deployment
    shell: "php {{doc_root}}/cli/akeeba-backup.php --profile=2"
    ignore_errors: True

  - name: create empty index.html files
    file: path="{{ doc_root }}/{{ item }}/index.html" state=touch owner="{{server_runs_as}}" group="{{server_runs_as_group}}"
    with_items:
      - "cache"
      - "tmp"
      - "logs"
      - "administrator/cache"

  - name: Unarchive artifact on remote server
    unarchive:
      src: "{{ workspace | default('') }}/{{ artifact_filename }}"
      dest: "{{ doc_root }}"
      copy: yes
      owner: "{{ server_runs_as }}"
      group: "{{ server_runs_as_group }}"

  - name: Create all wget cronjobs
    become: false
    tags: cron
    cron:
      name: "{{item.name}}"
      minute: "{{item.minute}}"
      hour: "{{item.hour}}"
      job: "/usr/bin/wget --no-check-certificate -qO- '{{item.url}}' &> /dev/null"
    with_items :
    - {
      name: "Easydiscuss cron",
      url: "https://{{ deploy_env_domain }}/index.php?option=com_easydiscuss&task=cron",
      minute: "*/5",
      hour: "*"
    }
    - {
      name: "Reminder cron",
      url: "https://{{ deploy_env_domain }}/index.php?option=com_jlike&task=remindersCron&tmpl=component",
      minute: "*",
      hour: "*/1"
    }
